language: ruby
rvm:
  - 2.0.0
addons:
  apt:
    packages:
      - vim
before_script:
  - bundle install
  - bundle show
script:
  - rake ci
install:
  - git clone https://github.com/kana/vim-vspec.git
