language: ruby
rvm:
  - 2.0.0
before_script:
  - bundle install
  - bundle show
  - sudo apt-get update
  - sudo apt-get install vim
script:
  - rake ci
install:
  - git clone https://github.com/kana/vim-vspec.git
